/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SWJNI */

#ifndef _Included_SWJNI
#define _Included_SWJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SWJNI
 * Method:    smithwaterman
 * Signature: (IIII[B[BIII[B[BII)I
 */
JNIEXPORT jint JNICALL Java_SWJNI_smithwaterman
  (JNIEnv *, jobject, jint, jint, jint, jint, jbyteArray, jbyteArray, jint, jint, jint, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
