#!/bin/bash
SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

if [ "$#" -lt 1 ]; then
  echo "Missing command"
  exit -1;
fi

trap 'kill $(jobs -p)' 1 2 3 15

output=`$SCRIPT_DIR/manager/client`

if [ $? -ne 0 ]; then
  exit 1
fi

output_arr=($output)
host=${output_arr[0]}
pid=${output_arr[1]}

# launch process
if [ -e "$1" ]; then
  ssh $host 'bash -s' < $1
else
  ssh $host $1
fi
ret=$?

$SCRIPT_DIR/manager/client $pid

if [ $ret -ne 0 ]; then
  exit $ret
fi
