################################################################################
## This script does the printreads stage
################################################################################
#!/usr/bin/env bash

# Import global variables
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/../globals.sh
source $DIR/common.sh

stage_name=printReads

# Prevent this script to be running alone
if [[ $0 != ${BASH_SOURCE[0]} ]]; then
  # Script is sourced by another shell
  cmd_name=`basename $0 2> /dev/null`
  if [[ "$cmd_name" != "fcs-genome" ]]; then
    log_error "This script should be started by 'fcs-genome'"
    return 1
  fi
else
  # Script is executed directly
  log_error "This script should be started by 'fcs-genome'"
  exit 1
fi

print_help() {
  echo "USAGE:"
  echo "fcs-genome printReads \\";
  echo "    -r <ref.fasta> \\";
  echo "    -i <input.bam> \\ ";
  echo "    -bqsr <calibrate.rpt> \\";
  echo "    -o <output_dir>";
  echo 
  echo "<input.bam> argument is the markduped bam file";
  echo "<calibrate.rpt> argument is the report file generated by bqsr stage";
  echo "<output_dir> argument is the directory to put the output results";
}

if [ $# -lt 1 ]; then
  print_help
  exit 1;
fi

# Get the input command
while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
  -r|--ref)
    ref_fasta="$2"
    shift # past argument
    ;;
  -i|--input)
    input="$2"
    shift # past argument
    ;;
  -bqsr)
    bqsr_rpt="$2"
    shift # past argument
    ;;
  -o|--output)
    output="$2"
    shift # past argument
    ;;
  -v|--verbose)
    verbose="$2"
    shift
    ;;
  -f|--force)
    force_flag=YES
    ;;
  -h|--help)
    help_req=YES
    ;;
  *)
    # unknown option
    ;;
  esac
  shift # past argument or value
done

# If no argument is given then print help message
if [ ! -z $help_req ];then
  print_help
  exit 0;
fi

# Check the input arguments
check_arg "-r" "ref_fasta" "$ref_genome"
check_arg "-i" "$input"
check_arg "-bqsr" "$bqsr_rpt"
check_arg "-o" "output" "${tmp_dir[1]}"
check_args

# Check the input
check_input $ref_fasta
check_input $input
check_input $bqsr_rpt


input_base_withsuffix=$(basename $input)
input_base=${input_base_withsuffix%%.*} 

# Check output
create_dir $output

chr_list="$(seq 1 22) X Y MT"
for chr in $chr_list; do
  # The splited bams are in tmp_dir[1], the recalibrated bams should be in [2]
  chr_recal_bam=${output}/${input_base}.recal.chr${chr}.bam
  check_output $chr_recal_bam
done

# Get absolute filepath for input/output
ref_fasta=$(readlink -f $ref_fasta)
input=$(readlink -f $input)
output=$(readlink -f $output)
bqsr_rpt=$(readlink -f $bqsr_rpt)

# Create the log directory
create_dir $log_dir

declare -A pid_table
declare -A output_table

# Start manager
start_ts=$(date +%s)
start_manager

trap "terminate" 1 2 3 15

# check if index already exists
if [ ! -f ${input}.bai ]; then
  log_warn "Cannot find index for $(basename $input), use samtool to index"
  start_ts=$(date +%s)
  $SAMTOOLS index $input
  end_ts=$(date +%s)
  log_info "Samtools index for $(basename $input) finishes in $((end_ts - start_ts))s"
fi

# Start the jobs
for chr in $chr_list; do
  chr_recal_bam=${output}/${input_base}.recal.chr${chr}.bam

  # TODO(yaoh) add the verbose option case here
  $DIR/../fcs-sh "$DIR/printReads_chr.sh $input $bqsr_rpt $chr_recal_bam $chr $ref_fasta " 2> $log_dir/printReads_chr${chr}.log 1>/dev/null &
  pid_table["$chr"]=$!
  output_table["$chr"]=$chr_recal_bam
done

# Wait on all the tasks
log_file=$log_dir/printReads.log
is_error=0
for chr in ${!pid_table[@]}; do
  pid=${pid_table[$chr]}
  wait "${pid}"
  if [ "$?" -gt 0 ]; then
    is_error=1
    log_error "Failed on chromosome $chr"
  fi

  # Concat log and remove the individual ones
  chr_log=$log_dir/printReads_chr${chr}.log
  cat $chr_log >> $log_file
  rm -f $log_dir/printReads_chr${chr}.log
done
end_ts=$(date +%s)

# Stop manager
stop_manager

unset pid_table
unset output_table

if [ "$is_error" -ne 0 ]; then
  log_error "Stage failed, please check logs in $log_file for details."
  exit 1
fi

log_info "Stage finishes in $((end_ts - start_ts))s"
rm -f ${output}/${input_base}.recal.chr*.bam.done
