#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/common.sh
source $DIR/settings.sh

# Usage: ./demux-agent run_id run_folder dest_dir
if [ $# -lt 3 ]; then
  echo "$0 run_id run_folder dest_dir"
  exit 1
fi

run_id=$1
run_folder=$2
dest_dir=$3

verbose=2
log_file=$log_dir/demux-agent-${run_id}.log

# check if the same run_id is running or not
lock_dir=/tmp/demux-${run_id}-lock
if mkdir $lock_dir; then
  log_info "Start demux for $run_id"
else
  echo "Another demux-agent for $run_id is running, exiting..." >&2
  exit -1
fi

if [ ! -f $run_folder/SampleSheet.csv ]; then
  log_error "Cannot find sample sheet in the run_folder"
  exit -1
fi

if [ ! -f $dest_dir/DemuxComplete.txt ]; then
  create_dir $dest_dir
 
  # start demultiplexing
  start_ts=$(date +%s)
  bcl2fastq -R $run_folder -o $dest_dir &>> $log_file
  end_ts=$(date +%s)
  
  echo "demux finished" > $dest_dir/DemuxComplete.txt
  log_info "Finished demultiplexing in $((end_ts - start_ts)) sec"

  #rm -r $run_folder &
else
  log_info "Demultiplexing for $run_id already finished"
fi
# experimental
cp $run_folder/SampleSheet.csv $dest_dir
scp -r $dest_dir $remote_fastq_loc &
rm -rf $lock_dir
