#!/usr/bin/env python
import argparse
import getpass
import json
import logging
import sys, getopt, signal
import sysv_ipc as ipc

parser = argparse.ArgumentParser()
parser.add_argument('-q', '--queue', dest='queue', nargs='?',
                     type=int, default=1027, help='id of the queue')

parser.add_argument('-i', '--input', dest='input', nargs='?',
                     default="data.json", help='input json file')

args = parser.parse_args()

# load json
with open(args.input) as fin:
  q = ipc.MessageQueue(args.queue, flags=ipc.IPC_CREAT)
  q.send(fin.read())
